alias: "Printer LED Ring "
description: Print Progress Display
trigger:
  - platform: state
    entity_id:
      - sensor.ke_progress
condition: []
action:
  - if:
      - condition: numeric_state
        entity_id: sensor.ke_progress
        above: 1
        below: 12.4
    then:
      - service: select.select_option
        target:
          entity_id: select.keled_preset
        data:
          option: printing_1
  - if:
      - condition: numeric_state
        entity_id: sensor.ke_progress
        above: 12.5
        below: 24.9
    then:
      - service: select.select_option
        target:
          entity_id: select.keled_preset
        data:
          option: printing_2
  - if:
      - condition: numeric_state
        entity_id: sensor.ke_progress
        above: 25
        below: 37.4
    then:
      - service: select.select_option
        target:
          entity_id: select.keled_preset
        data:
          option: printing_3
  - if:
      - condition: numeric_state
        entity_id: sensor.ke_progress
        above: 37.5
        below: 49.9
    then:
      - service: select.select_option
        target:
          entity_id: select.keled_preset
        data:
          option: printing_4
  - if:
      - condition: numeric_state
        entity_id: sensor.ke_progress
        above: 50
        below: 62.4
    then:
      - service: select.select_option
        target:
          entity_id: select.keled_preset
        data:
          option: printing_5
  - if:
      - condition: numeric_state
        entity_id: sensor.ke_progress
        above: 62.5
        below: 74.9
    then:
      - service: select.select_option
        target:
          entity_id: select.keled_preset
        data:
          option: printing_6
  - if:
      - condition: numeric_state
        entity_id: sensor.ke_progress
        above: 75
        below: 87.4
    then:
      - service: select.select_option
        target:
          entity_id: select.keled_preset
        data:
          option: printing_7
  - if:
      - condition: numeric_state
        entity_id: sensor.ke_progress
        above: 87.5
        below: 99.9
    then:
      - service: select.select_option
        target:
          entity_id: select.keled_preset
        data:
          option: printing_8
  - if:
      - condition: numeric_state
        entity_id: sensor.ke_progress
        above: 99.9
    then:
      - service: select.select_option
        target:
          entity_id: select.keled_preset
        data:
          option: printing_complete
mode: single
