; HEADER_BLOCK_START
; generated by OrcaSlicer 2.0.0 on 2024-03-30 at 19:10:49
; total layer number: 2
; filament_density: 1.27
; filament_diameter: 1.75
; max_z_height: 0.40
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 96x96 700
; iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAB00lEQVR4Ae3YO66DQAyFYW8uPauhTs
; uW6FkNi8gVBRKK7gQw87A9/yeNlJZzPBhFBAAAAAAAAAAAaIzj+BbUtwW/rutnO9tviqhoD/77UEIF
; qfApobCz4CmioLvhU0Imx0X7pASKUHgaPLfhgdzhU8JFpYKniAtqhU8JX2oHTxEHrcPvtoQcn5clSu
; iiCGvBd3UbrIcftgQvwYcswlPgoUqwuGiflOCqCE/hhrsNngINVYKnEMMV4Sm4UCVEWrRPSmhShKeQ
; ahUhNTD1v0soWoSnMFoXIbl5CiBUCZ4eOlwRnh7U6pmm6SN3sWjznNfr9Za7PD2g1TPP8/2pJ/w8R/
; XK8fSAVg9T3/CwaBse0ViWxdVDWjyqqacEI+HvttcQRVw/6kV7hhLOT7apT2Epp4/UMgwDr6TDKT71
; KdwG5f84uUvo8TYUW7RaPZXQ7JVzpodXkngQ8TaYnfqUSLeh+aLV8v656m7qUzyWECb8nZfPVXOfl7
; lZLiHc1KdYXNDSGysLupupT2lZQvfh72ov6PCLVqtGCUz9iZILWnBdztvA1CvluA1u/8exQrugWbSZ
; 3SmBV04hZ7eBqa/kvxKY+sqOC1rQxvZ/kgAAAAAAAAAAAI0/5GN9tpk/5EUAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; THUMBNAIL_BLOCK_START

;
; thumbnail begin 300x300 2280
; iVBORw0KGgoAAAANSUhEUgAAASwAAAEsCAYAAAB5fY51AAAGdElEQVR4Ae3bwU3kShiFUSc3e6JhzZ
; YA2BMHe6IhiHnqeepRDzSN23bZ/606R/oSAPuqVHJPEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAw/v4+Ph96vHx8WkCqOo8VpejZbiAUk6j9HmsPg
; /XBHC0W0NltIAy5o6V4QIOs2SojBawu7Vj5UIeaO6ni3WnLaCEFkNltIBNtTpVGS5gU3sOldECFjtq
; rC5Hy3ABNx09VE5bwCzVxspoAV/sfbFuuIBFEobKaAFxY2W4YEBJw2S0YGBJgzR3tAwXdCblYt1pCw
; aXNDxGCwaWNDiGCwaVNDBGCwaWNCytR8twQVFJY7L3cE1AHUkDYrRgUL1/rmC4oBNJQ2G0YGBJA1F1
; tAwXNJY0CinDNQHbSxqCtNEyXLARF+v7DdcELJf0whstGFjSi264YFBJL7bRgoElvdCjjJbhgk9crN
; cfrglwqjJaEMCpynBBhKQXVEaLgSW9mLo9WoaLbiW9jLpvuCboSdILKKPFoFysGy6IkPSiyWgxsKQX
; TG0yXJSX9EKpfUaLspJeJO2Xzx8oxcW65mS0OFzSC6PjM1ocwqlKazJc7CbpxVDdjBbNJb0Qqp8LeZ
; pIegmUl9FiM0kPvnIzWqziYl1HZLi4W9IDrv4yWsyW9GCr31zIc1PSw6xxMlp8kfQAa7yctvjDxbqS
; MloDS3pQpXNGa0BJD6h0LcM1gKQHUvopo9WxpAdRmpsL+c4kPXzS0oxWB5IeOGltRiuUzxU0coYrSN
; KDJbXKaAVIeqCk1rmQLyrpIZL2zmgVkvTgSEdltA7mYl26P8N1gKQHRKqW0dpR0oMhVc5wNZT0IEgp
; Ga0Gkh4AKS2fP2zExbq0X0ZrhaR/tNRLRutOTlXS8RmuGZL+oVLvGa0bkv6R0ii5kP8k6Z8njZrRmo
; yVlNSwo+ViXcptqOFK+sdIut4Qo5X0D5H0c10OV9I/QNJ9dTVaSX94ScuK//zBxbo0Xr9+/Xqa0iT9
; gSVt0/Pzc95gJf2BJW3TaaxOTSmS/riStuk8VMZKUukMlaTyvb29GStJ9YsbKp8rSGPmVCWpfOehiv
; pkIekPLGmbnKoklc/FuqSIXKxLisipSlL5XKxLisipSlL5/A5QUkQu1iWVz+cKkiJyqpIUkVOVpPK5
; WJcUkaGSVD4X65Iiihuqk4eHh6f39/eoP7SkdUWO1dnr6+vv02gZLqnvIn8HeM3ppHUerqR/gKR5RZ
; +qrjFaUn9FXqzf4zRahkvKr+uhuuS0JeXW/anqOy7kpayGHKpLTltSRsOP1SWjJdUs8neAe3Dakmpl
; qH5gtKTjG/ZifSmfP0jHZKgWctqS9s1YbcDnD1LbuvkdYBVOW1KbnKoaMVrSdrlY34kLeWldhmpnTl
; vSsozVgVzIS/NysV6E05Z0O6eqgoyW9G9+B1ic05b0f4YqhNHSyPlcIZQLeY2WoQrntKVRMlYdcdpS
; r7lY75TTlnrLUHXOaKmHXKwPxu8RlZqhGpTTltIyVriQV/n8DpB/OG2pak5VXGW0VCmfKzCL4dLRGS
; ruYrR0RD5XYBUX8torQ8UmnLbUOmPF5oyWts7FOk05bWmrDBW7MFpak4t1DuH3iLo3Q8WhnLY0N2NF
; GT5/0Hf5HSAlOW3pc05VlGa0dMrFOlFcyI+boSKS09ZYOVXRBRfy/edina44bfU/VhP0xmj1N1TGiq
; 45bfUzVhOMwGhl5mKdobmQz8lQweS0ZawgkNNW3aHyuQJc4bRVb6wm4HtG69hcrMMCfo+4f4YKVnDa
; MlYQx4V8+6FysQ4bctpqN1YT0IbR2m6ojBXswGlr/VhNwH6M1n35XAEKcCH/c4YKCnHaMlYQx2h9HS
; pjBYU5bTlVQZRRR8vFOgQb6feIhgo6MMJpy1hBZ3r8/MHvAKFjPZ22nKpgAOmj5WIdBpR4IW+oYGAp
; py2nKuCvyhfyhgr4ouJpy1gBN1UYLb8DBGY78rRlqIC77T1aLtaB1fb4/MFQAZtpedoyVkATW37+4H
; eAQHNbnLacqoDdLB0tF+vAYe65kDdUwOHmnLaMFVDKtQt5F+tAWZenLacqIMLLy4uxAgAAAAAAAAAA
; AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgj/8Aa36W25aC6j
; wAAAAASUVORK5CYII=
; thumbnail end
; THUMBNAIL_BLOCK_END

; external perimeters extrusion width = 0.50mm
; perimeters extrusion width = 0.50mm
; infill extrusion width = 0.50mm
; solid infill extrusion width = 0.50mm
; top infill extrusion width = 0.50mm
; first layer extrusion width = 0.50mm

; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=Diffuser_id_0_copy_0 CENTER=110,110 POLYGON=[[90.5,94.5],[129.5,94.5],[129.5,125.5],[90.5,125.5],[90.5,94.5]]
M73 P0 R2
;TYPE:Custom
START_PRINT BED_TEMP=80 EXTRUDER_TEMP=235
G90
G21
M83 ; use relative distances for extrusion
; filament start gcode
M106 S0
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.2
G92 E0

G1 E-.5 F2400
TIMELAPSE_TAKE_FRAME
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=500 ACCEL_TO_DECEL=250
SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=7
; printing object Diffuser id:0 copy 0
EXCLUDE_OBJECT_START NAME=Diffuser_id_0_copy_0
G1 Z.2 F18000
G1 X128.793 Y124.793
G1 Z.2
G1 E.5 F2400
;TYPE:Inner wall
;WIDTH:0.5
G1 F3000
G1 X91.207 Y124.793 E1.35707
M73 P1 R2
G1 X91.207 Y95.207 E1.06823
G1 X128.793 Y95.207 E1.35707
M73 P2 R2
G1 X128.793 Y124.753 E1.06678
M73 P3 R2
G1 X129.25 Y125.25 F18000
;TYPE:Outer wall
G1 F3000
G1 X90.75 Y125.25 E1.39008
G1 X90.75 Y94.75 E1.10123
M73 P4 R2
G1 X129.25 Y94.75 E1.39008
G1 X129.25 Y125.21 E1.09979
M73 P5 R2
G1 E-.35 F2400
;WIPE_START
G1 F3000
G1 X128.25 Y125.211 E-.15
;WIPE_END
TIMELAPSE_TAKE_FRAME
G1 Z.4 F18000
G1 X128.61 Y124.404
G1 Z.4
G1 Z.2
G1 E.5 F2400
;TYPE:Bottom surface
;WIDTH:0.500199
G1 F5904.492
G1 X91.596 Y124.404 E1.33703
G1 X91.596 Y123.947 E.01652
G1 X128.404 Y123.947 E1.3296
M73 P6 R2
G1 X128.404 Y123.49 E.01652
G1 X91.596 Y123.49 E1.3296
G1 X91.596 Y123.032 E.01652
G1 X128.404 Y123.032 E1.3296
M73 P7 R2
G1 X128.404 Y122.575 E.01652
G1 X91.596 Y122.575 E1.3296
G1 X91.596 Y122.118 E.01652
G1 X128.404 Y122.118 E1.3296
G1 X128.404 Y121.661 E.01652
G1 X91.596 Y121.661 E1.3296
M73 P8 R2
G1 X91.596 Y121.203 E.01652
G1 X128.404 Y121.203 E1.3296
G1 X128.404 Y120.746 E.01652
G1 X91.596 Y120.746 E1.3296
M73 P9 R2
G1 X91.596 Y120.289 E.01652
G1 X128.404 Y120.289 E1.3296
G1 X128.404 Y119.832 E.01652
G1 X91.596 Y119.832 E1.3296
M73 P10 R2
G1 X91.596 Y119.374 E.01652
G1 X128.404 Y119.374 E1.3296
G1 X128.404 Y118.917 E.01652
G1 X91.596 Y118.917 E1.3296
G1 X91.596 Y118.46 E.01652
G1 X128.404 Y118.46 E1.3296
M73 P11 R2
G1 X128.404 Y118.002 E.01652
G1 X91.596 Y118.002 E1.3296
G1 X91.596 Y117.545 E.01652
G1 X128.404 Y117.545 E1.3296
M73 P12 R2
G1 X128.404 Y117.088 E.01652
G1 X91.596 Y117.088 E1.3296
G1 X91.596 Y116.631 E.01652
G1 X128.404 Y116.631 E1.3296
G1 X128.404 Y116.173 E.01652
M73 P13 R2
G1 X91.596 Y116.173 E1.3296
G1 X91.596 Y115.716 E.01652
G1 X128.404 Y115.716 E1.3296
G1 X128.404 Y115.259 E.01652
G1 X91.596 Y115.259 E1.3296
M73 P14 R1
G1 X91.596 Y114.801 E.01652
G1 X128.404 Y114.801 E1.3296
G1 X128.404 Y114.344 E.01652
G1 X91.596 Y114.344 E1.3296
M73 P15 R1
G1 X91.596 Y113.887 E.01652
G1 X128.404 Y113.887 E1.3296
G1 X128.404 Y113.43 E.01652
G1 X91.596 Y113.43 E1.3296
G1 X91.596 Y112.972 E.01652
G1 X128.404 Y112.972 E1.3296
M73 P16 R1
G1 X128.404 Y112.515 E.01652
G1 X91.596 Y112.515 E1.3296
G1 X91.596 Y112.058 E.01652
G1 X128.404 Y112.058 E1.3296
M73 P17 R1
G1 X128.404 Y111.601 E.01652
G1 X91.596 Y111.6 E1.3296
G1 X91.596 Y111.143 E.01652
G1 X128.404 Y111.143 E1.3296
M73 P18 R1
G1 X128.404 Y110.686 E.01652
G1 X91.596 Y110.686 E1.3296
G1 X91.596 Y110.229 E.01652
G1 X128.404 Y110.229 E1.3296
G1 X128.404 Y109.771 E.01652
G1 X91.596 Y109.771 E1.3296
M73 P19 R1
G1 X91.596 Y109.314 E.01652
G1 X128.404 Y109.314 E1.3296
G1 X128.404 Y108.857 E.01652
G1 X91.596 Y108.857 E1.3296
M73 P20 R1
G1 X91.596 Y108.4 E.01652
G1 X128.404 Y108.4 E1.3296
G1 X128.404 Y107.942 E.01652
G1 X91.596 Y107.942 E1.3296
G1 X91.596 Y107.485 E.01652
G1 X128.404 Y107.485 E1.3296
M73 P21 R1
G1 X128.404 Y107.028 E.01652
G1 X91.596 Y107.028 E1.3296
G1 X91.596 Y106.57 E.01652
G1 X128.404 Y106.57 E1.3296
M73 P22 R1
G1 X128.404 Y106.113 E.01652
G1 X91.596 Y106.113 E1.3296
G1 X91.596 Y105.656 E.01652
G1 X128.404 Y105.656 E1.3296
M73 P23 R1
G1 X128.404 Y105.199 E.01652
G1 X91.596 Y105.199 E1.3296
G1 X91.596 Y104.741 E.01652
G1 X128.404 Y104.741 E1.3296
G1 X128.404 Y104.284 E.01652
G1 X91.596 Y104.284 E1.3296
M73 P24 R1
G1 X91.596 Y103.827 E.01652
G1 X128.404 Y103.827 E1.3296
G1 X128.404 Y103.369 E.01652
G1 X91.596 Y103.369 E1.3296
M73 P25 R1
G1 X91.596 Y102.912 E.01652
G1 X128.404 Y102.912 E1.3296
G1 X128.404 Y102.455 E.01652
G1 X91.596 Y102.455 E1.3296
G1 X91.596 Y101.998 E.01652
M73 P26 R1
G1 X128.404 Y101.998 E1.3296
G1 X128.404 Y101.54 E.01652
G1 X91.596 Y101.54 E1.3296
G1 X91.596 Y101.083 E.01652
G1 X128.404 Y101.083 E1.3296
M73 P27 R1
G1 X128.404 Y100.626 E.01652
G1 X91.596 Y100.626 E1.3296
G1 X91.596 Y100.169 E.01652
G1 X128.404 Y100.169 E1.3296
M73 P28 R1
G1 X128.404 Y99.711 E.01652
G1 X91.596 Y99.711 E1.3296
G1 X91.596 Y99.254 E.01652
G1 X128.404 Y99.254 E1.3296
G1 X128.404 Y98.797 E.01652
G1 X91.596 Y98.797 E1.3296
M73 P29 R1
G1 X91.596 Y98.339 E.01652
G1 X128.404 Y98.339 E1.3296
G1 X128.404 Y97.882 E.01652
G1 X91.596 Y97.882 E1.3296
M73 P30 R1
G1 X91.596 Y97.425 E.01652
G1 X128.404 Y97.425 E1.3296
G1 X128.404 Y96.968 E.01652
G1 X91.596 Y96.968 E1.3296
M73 P31 R1
G1 X91.596 Y96.51 E.01652
G1 X128.404 Y96.51 E1.3296
G1 X128.404 Y96.053 E.01652
G1 X91.596 Y96.053 E1.3296
G1 X91.596 Y95.596 E.01652
G1 X128.61 Y95.596 E1.33703
; stop printing object Diffuser id:0 copy 0
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
;0.4
G92 E0

M73 P32 R1
G1 E-.35 F2400
;WIPE_START
G1 F5904.492
G1 X127.61 Y95.596 E-.15
;WIPE_END
EXCLUDE_OBJECT_END NAME=Diffuser_id_0_copy_0
TIMELAPSE_TAKE_FRAME
;_SET_FAN_SPEED_CHANGING_LAYER
SET_VELOCITY_LIMIT ACCEL=5000 ACCEL_TO_DECEL=2500
M104 S230 ; set nozzle temperature
; printing object Diffuser id:0 copy 0
SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=8
EXCLUDE_OBJECT_START NAME=Diffuser_id_0_copy_0
G1 Z.4 F18000
G1 X128.793 Y124.793 Z.4
G1 E.5 F2400
SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=7
;TYPE:Inner wall
;WIDTH:0.5
G1 F1200
G1 X91.207 Y124.793 E1.35707
M73 P33 R1
G1 X91.207 Y95.207 E1.06823
M73 P34 R1
G1 X128.793 Y95.207 E1.35707
M73 P36 R1
G1 X128.793 Y124.753 E1.06678
SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=8
M73 P37 R1
G1 X129.25 Y125.25 F18000
SET_VELOCITY_LIMIT ACCEL=2500 ACCEL_TO_DECEL=1250
;TYPE:Outer wall
G1 F1200
G1 X90.75 Y125.25 E1.39008
M73 P38 R1
G1 X90.75 Y94.75 E1.10123
M73 P39 R1
G1 X129.25 Y94.75 E1.39008
M73 P41 R1
G1 X129.25 Y125.21 E1.09979
M73 P42 R1
G1 E-.35 F2400
;WIPE_START
G1 F1200
G1 X128.25 Y125.211 E-.15
;WIPE_END
TIMELAPSE_TAKE_FRAME
SET_VELOCITY_LIMIT ACCEL=5000 ACCEL_TO_DECEL=2500
G1 Z.6 F18000
G1 X128.61 Y124.404
G1 Z.6
G1 Z.4
G1 E.5 F2400
SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=7
;TYPE:Top surface
;WIDTH:0.500199
G1 F1800
G1 X91.596 Y124.404 E1.33703
M73 P43 R1
G1 X91.596 Y123.947 E.01652
G1 X128.404 Y123.947 E1.3296
M73 P44 R1
G1 X128.404 Y123.49 E.01652
G1 X91.596 Y123.49 E1.3296
M73 P45 R1
G1 X91.596 Y123.032 E.01652
G1 X128.404 Y123.032 E1.3296
M73 P46 R1
G1 X128.404 Y122.575 E.01652
G1 X91.596 Y122.575 E1.3296
G1 X91.596 Y122.118 E.01652
G1 X128.404 Y122.118 E1.3296
M73 P47 R1
G1 X128.404 Y121.661 E.01652
G1 X91.596 Y121.661 E1.3296
M73 P48 R1
G1 X91.596 Y121.203 E.01652
G1 X128.404 Y121.203 E1.3296
M73 P49 R1
G1 X128.404 Y120.746 E.01652
G1 X91.596 Y120.746 E1.3296
M73 P50 R1
G1 X91.596 Y120.289 E.01652
G1 X128.404 Y120.289 E1.3296
M73 P51 R1
G1 X128.404 Y119.832 E.01652
G1 X91.596 Y119.832 E1.3296
M73 P52 R1
G1 X91.596 Y119.374 E.01652
G1 X128.404 Y119.374 E1.3296
M73 P53 R1
G1 X128.404 Y118.917 E.01652
G1 X91.596 Y118.917 E1.3296
M73 P54 R1
G1 X91.596 Y118.46 E.01652
G1 X128.404 Y118.46 E1.3296
M73 P55 R1
G1 X128.404 Y118.002 E.01652
G1 X91.596 Y118.002 E1.3296
G1 X91.596 Y117.545 E.01652
G1 X128.404 Y117.545 E1.3296
M73 P56 R1
G1 X128.404 Y117.088 E.01652
G1 X91.596 Y117.088 E1.3296
M73 P57 R0
G1 X91.596 Y116.631 E.01652
G1 X128.404 Y116.631 E1.3296
M73 P58 R0
G1 X128.404 Y116.173 E.01652
G1 X91.596 Y116.173 E1.3296
M73 P59 R0
G1 X91.596 Y115.716 E.01652
G1 X128.404 Y115.716 E1.3296
M73 P60 R0
G1 X128.404 Y115.259 E.01652
G1 X91.596 Y115.259 E1.3296
M73 P61 R0
G1 X91.596 Y114.801 E.01652
G1 X128.404 Y114.801 E1.3296
M73 P62 R0
G1 X128.404 Y114.344 E.01652
G1 X91.596 Y114.344 E1.3296
M73 P63 R0
G1 X91.596 Y113.887 E.01652
G1 X128.404 Y113.887 E1.3296
M73 P64 R0
G1 X128.404 Y113.43 E.01652
G1 X91.596 Y113.43 E1.3296
G1 X91.596 Y112.972 E.01652
G1 X128.404 Y112.972 E1.3296
M73 P65 R0
G1 X128.404 Y112.515 E.01652
G1 X91.596 Y112.515 E1.3296
M73 P66 R0
G1 X91.596 Y112.058 E.01652
G1 X128.404 Y112.058 E1.3296
M73 P67 R0
G1 X128.404 Y111.601 E.01652
G1 X91.596 Y111.6 E1.3296
M73 P68 R0
G1 X91.596 Y111.143 E.01652
G1 X128.404 Y111.143 E1.3296
M73 P69 R0
G1 X128.404 Y110.686 E.01652
G1 X91.596 Y110.686 E1.3296
M73 P70 R0
G1 X91.596 Y110.229 E.01652
G1 X128.404 Y110.229 E1.3296
M73 P71 R0
G1 X128.404 Y109.771 E.01652
G1 X91.596 Y109.771 E1.3296
M73 P72 R0
G1 X91.596 Y109.314 E.01652
G1 X128.404 Y109.314 E1.3296
G1 X128.404 Y108.857 E.01652
M73 P73 R0
G1 X91.596 Y108.857 E1.3296
G1 X91.596 Y108.4 E.01652
G1 X128.404 Y108.4 E1.3296
M73 P74 R0
G1 X128.404 Y107.942 E.01652
G1 X91.596 Y107.942 E1.3296
M73 P75 R0
G1 X91.596 Y107.485 E.01652
G1 X128.404 Y107.485 E1.3296
M73 P76 R0
G1 X128.404 Y107.028 E.01652
G1 X91.596 Y107.028 E1.3296
M73 P77 R0
G1 X91.596 Y106.57 E.01652
G1 X128.404 Y106.57 E1.3296
M73 P78 R0
G1 X128.404 Y106.113 E.01652
G1 X91.596 Y106.113 E1.3296
M73 P79 R0
G1 X91.596 Y105.656 E.01652
G1 X128.404 Y105.656 E1.3296
M73 P80 R0
G1 X128.404 Y105.199 E.01652
G1 X91.596 Y105.199 E1.3296
M73 P81 R0
G1 X91.596 Y104.741 E.01652
G1 X128.404 Y104.741 E1.3296
G1 X128.404 Y104.284 E.01652
G1 X91.596 Y104.284 E1.3296
M73 P82 R0
G1 X91.596 Y103.827 E.01652
G1 X128.404 Y103.827 E1.3296
M73 P83 R0
G1 X128.404 Y103.369 E.01652
G1 X91.596 Y103.369 E1.3296
M73 P84 R0
G1 X91.596 Y102.912 E.01652
G1 X128.404 Y102.912 E1.3296
M73 P85 R0
G1 X128.404 Y102.455 E.01652
G1 X91.596 Y102.455 E1.3296
M73 P86 R0
G1 X91.596 Y101.998 E.01652
G1 X128.404 Y101.998 E1.3296
M73 P87 R0
G1 X128.404 Y101.54 E.01652
G1 X91.596 Y101.54 E1.3296
M73 P88 R0
G1 X91.596 Y101.083 E.01652
G1 X128.404 Y101.083 E1.3296
M73 P89 R0
G1 X128.404 Y100.626 E.01652
G1 X91.596 Y100.626 E1.3296
M73 P90 R0
G1 X91.596 Y100.169 E.01652
G1 X128.404 Y100.169 E1.3296
G1 X128.404 Y99.711 E.01652
G1 X91.596 Y99.711 E1.3296
M73 P91 R0
G1 X91.596 Y99.254 E.01652
G1 X128.404 Y99.254 E1.3296
M73 P92 R0
G1 X128.404 Y98.797 E.01652
G1 X91.596 Y98.797 E1.3296
M73 P93 R0
G1 X91.596 Y98.339 E.01652
G1 X128.404 Y98.339 E1.3296
M73 P94 R0
G1 X128.404 Y97.882 E.01652
G1 X91.596 Y97.882 E1.3296
M73 P95 R0
G1 X91.596 Y97.425 E.01652
G1 X128.404 Y97.425 E1.3296
M73 P96 R0
G1 X128.404 Y96.968 E.01652
G1 X91.596 Y96.968 E1.3296
M73 P97 R0
G1 X91.596 Y96.51 E.01652
G1 X128.404 Y96.51 E1.3296
M73 P98 R0
G1 X128.404 Y96.053 E.01652
G1 X91.596 Y96.053 E1.3296
M73 P99 R0
G1 X91.596 Y95.596 E.01652
G1 X128.61 Y95.596 E1.33703
; stop printing object Diffuser id:0 copy 0
G1 E-.35 F2400
;WIPE_START
G1 F1800
G1 X127.61 Y95.596 E-.15
;WIPE_END
EXCLUDE_OBJECT_END NAME=Diffuser_id_0_copy_0
M106 S0
;TYPE:Custom
; filament end gcode 
END_PRINT
M73 P100 R0
; EXECUTABLE_BLOCK_END

; filament used [mm] = 191.46
; filament used [cm3] = 0.46
; filament used [g] = 0.58
; filament cost = 0.02; total filament used [g] = 0.58
; total filament cost = 0.02
; total layers count = 2
; estimated printing time (normal mode) = 2m 18s

; CONFIG_BLOCK_START
; accel_to_decel_enable = 1
; accel_to_decel_factor = 50%
; activate_air_filtration = 0
; activate_chamber_temp_control = 0
; adaptive_bed_mesh_margin = 0
; additional_cooling_fan_speed = 0
; alternate_extra_wall = 0
; auxiliary_fan = 0
; bbl_calib_mark_logo = 1
; bbl_use_printhost = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_exclude_area = 0x0
; bed_mesh_max = 99999,99999
; bed_mesh_min = -99999,-99999
; bed_mesh_probe_distance = 50,50
; before_layer_change_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]\nG92 E0\n
; best_object_pos = 0.5,0.5
; bottom_shell_layers = 1
; bottom_shell_thickness = 0
; bottom_solid_infill_flow_ratio = 1
; bottom_surface_pattern = alignedrectilinear
; bridge_acceleration = 50%
; bridge_angle = 0
; bridge_density = 100%
; bridge_flow = 0.95
; bridge_no_support = 0
; bridge_speed = 100
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_object_gap = 0.1
; brim_type = no_brim
; brim_width = 5
; chamber_temperature = 0
; change_extrusion_role_gcode = 
; change_filament_gcode = PAUSE
; close_fan_the_first_x_layers = 6
; complete_print_exhaust_fan_speed = 80
; cool_plate_temp = 70
; cool_plate_temp_initial_layer = 70
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; counterbore_hole_bridging = none
; curr_bed_type = High Temp Plate
; default_acceleration = 5000
; default_filament_colour = #FFFFFF
; default_filament_profile = "Creality Generic PLA @Ender-3V3-all"
; default_jerk = 7
; default_print_profile = 0.20mm Standard @Creality Ender3V3KE
; deretraction_speed = 40
; detect_narrow_internal_solid_infill = 0
; detect_overhang_wall = 1
; detect_thin_wall = 1
; different_settings_to_system = bottom_shell_layers;bottom_surface_pattern;detect_narrow_internal_solid_infill;ensure_vertical_shell_thickness;gap_infill_speed;infill_direction;infill_wall_overlap;inner_wall_line_width;inner_wall_speed;internal_solid_infill_line_width;internal_solid_infill_pattern;internal_solid_infill_speed;line_width;outer_wall_line_width;outer_wall_speed;slow_down_layers;sparse_infill_density;sparse_infill_line_width;sparse_infill_pattern;sparse_infill_speed;support_line_width;top_shell_layers;top_surface_line_width;top_surface_pattern;top_surface_speed;wall_generator;close_fan_the_first_x_layers;default_filament_colour;fan_max_speed;fan_min_speed;filament_vendor;hot_plate_temp;hot_plate_temp_initial_layer;nozzle_temperature;nozzle_temperature_initial_layer;overhang_fan_threshold;reduce_fan_stop_start_freq;machine_end_gcode;machine_start_gcode;print_host;time_lapse_gcode
; disable_m73 = 0
; dont_filter_internal_bridges = disabled
; draft_shield = disabled
; during_print_exhaust_fan_speed = 60
; elefant_foot_compensation = 0
; elefant_foot_compensation_layers = 1
; emit_machine_limits_to_gcode = 1
; enable_arc_fitting = 0
; enable_filament_ramming = 1
; enable_overhang_bridge_fan = 1
; enable_overhang_speed = 1
; enable_pressure_advance = 0
; enable_prime_tower = 0
; enable_support = 0
; enforce_support_layers = 0
; eng_plate_temp = 70
; eng_plate_temp_initial_layer = 70
; ensure_vertical_shell_thickness = none
; exclude_object = 1
; extra_loading_move = -2
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height_to_lid = 34
; extruder_clearance_height_to_rod = 47
; extruder_clearance_radius = 90
; extruder_colour = #FCE94F
; extruder_offset = 0x0
; fan_cooling_layer_time = 30
; fan_kickstart = 0
; fan_max_speed = 0
; fan_min_speed = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; filament_colour = #FFFFFF
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 30
; filament_density = 1.27
; filament_diameter = 1.75
; filament_end_gcode = "; filament end gcode \n"
; filament_flow_ratio = 0.95
; filament_ids = GFG99
; filament_is_support = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 9
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Elagoo Hyper PETG - glass"
; filament_shrink = 100%
; filament_soluble = 0
; filament_start_gcode = "; filament start gcode\n"
; filament_toolchange_delay = 0
; filament_type = PETG
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Elagoo
; filename_format = {input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode
; filter_out_gap_fill = 0
; first_layer_print_sequence = 0
; flush_into_infill = 0
; flush_into_objects = 0
; flush_into_support = 1
; flush_multiplier = 0.3
; flush_volumes_matrix = 0
; flush_volumes_vector = 140,140
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_first_layer = 0
; fuzzy_skin_point_distance = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_target = everywhere
; gap_infill_speed = 30
; gcode_add_line_number = 0
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = 1
; has_scarf_joint_seam = 0
; head_wrap_detect_zone = 
; high_current_on_filament_swap = 0
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; hot_plate_temp = 75
; hot_plate_temp_initial_layer = 80
; independent_support_layer_height = 1
; infill_anchor = 400%
; infill_anchor_max = 20
; infill_combination = 0
; infill_direction = 0
; infill_jerk = 8
; infill_wall_overlap = 15%
; inherits_group = "0.20mm Standard @Creality Ender3V3KE";"Creality Generic PETG @Ender-3V3-all";"Creality Ender-3 V3 KE 0.4 nozzle"
; initial_layer_acceleration = 500
; initial_layer_infill_speed = 105
; initial_layer_jerk = 7
; initial_layer_line_width = 0.5
; initial_layer_min_bead_width = 85%
; initial_layer_print_height = 0.2
; initial_layer_speed = 50
; initial_layer_travel_speed = 100%
; inner_wall_acceleration = 5000
; inner_wall_jerk = 7
; inner_wall_line_width = 0.5
; inner_wall_speed = 20
; interface_shells = 0
; internal_bridge_flow = 1
; internal_bridge_speed = 150%
; internal_solid_infill_acceleration = 100%
; internal_solid_infill_line_width = 0.5
; internal_solid_infill_pattern = alignedrectilinear
; internal_solid_infill_speed = 30
; ironing_angle = -1
; ironing_flow = 15%
; ironing_pattern = zig-zag
; ironing_spacing = 0.1
; ironing_speed = 44
; ironing_type = no ironing
; is_infill_first = 0
; layer_change_gcode = 
; layer_height = 0.2
; line_width = 0.5
; machine_end_gcode = END_PRINT
; machine_load_filament_time = 11
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 8000,8000
; machine_max_acceleration_retracting = 5000,5000
; machine_max_acceleration_travel = 8000,8000
; machine_max_acceleration_x = 8000,8000
; machine_max_acceleration_y = 8000,8000
; machine_max_acceleration_z = 500,500
; machine_max_jerk_e = 5,5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.4,0.4
; machine_max_speed_e = 100,100
; machine_max_speed_x = 500,500
; machine_max_speed_y = 500,500
; machine_max_speed_z = 30,30
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; machine_pause_gcode = PAUSE
; machine_start_gcode = START_PRINT BED_TEMP=[bed_temperature_initial_layer_single] EXTRUDER_TEMP=[nozzle_temperature_initial_layer]
; machine_unload_filament_time = 0
; make_overhang_printable = 0
; make_overhang_printable_angle = 55
; make_overhang_printable_hole_size = 0
; manual_filament_change = 1
; max_bridge_length = 10
; max_layer_height = 0.32
; max_travel_detour_distance = 0
; max_volumetric_extrusion_rate_slope = 0
; max_volumetric_extrusion_rate_slope_segment_length = 3
; min_bead_width = 85%
; min_feature_size = 25%
; min_layer_height = 0.08
; min_length_factor = 0.5
; min_width_top_surface = 300%
; minimum_sparse_infill_area = 10
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; nozzle_hrc = 0
; nozzle_temperature = 230
; nozzle_temperature_initial_layer = 235
; nozzle_temperature_range_high = 270
; nozzle_temperature_range_low = 220
; nozzle_type = brass
; nozzle_volume = 0
; only_one_wall_first_layer = 0
; only_one_wall_top = 0
; ooze_prevention = 0
; outer_wall_acceleration = 2500
; outer_wall_jerk = 8
; outer_wall_line_width = 0.5
; outer_wall_speed = 20
; overhang_1_4_speed = 0
; overhang_2_4_speed = 20
; overhang_3_4_speed = 15
; overhang_4_4_speed = 10
; overhang_fan_speed = 90
; overhang_fan_threshold = 50%
; overhang_reverse = 0
; overhang_reverse_internal_only = 0
; overhang_reverse_threshold = 50%
; overhang_speed_classic = 0
; parking_pos_retraction = 92
; post_process = 
; precise_outer_wall = 0
; preferred_orientation = 0
; pressure_advance = 0.02
; prime_tower_brim_width = 3
; prime_tower_width = 60
; prime_volume = 45
; print_compatible_printers = "Creality Ender-3 V3 KE 0.4 nozzle"
; print_flow_ratio = 1
; print_order = default
; print_sequence = by layer
; print_settings_id = 0.20mm
; printable_area = 0x0,220x0,220x220,0x220
; printable_height = 240
; printer_model = Creality Ender-3 V3 KE
; printer_notes = 
; printer_settings_id = Creality Ender-3 V3 KE
; printer_structure = i3
; printer_technology = FFF
; printer_variant = 0.4
; printhost_authorization_type = key
; printhost_ssl_ignore_revoke = 0
; printing_by_object_gcode = 
; purge_in_prime_tower = 1
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 2
; raft_layers = 0
; reduce_crossing_wall = 0
; reduce_fan_stop_start_freq = 0
; reduce_infill_retraction = 1
; required_nozzle_HRC = 0
; resolution = 0.012
; retract_before_wipe = 70%
; retract_length_toolchange = 1
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_enforce = All Surfaces
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_when_changing_layer = 1
; retraction_length = 0.5
; retraction_minimum_travel = 2
; retraction_speed = 40
; role_based_wipe_speed = 1
; scan_first_layer = 0
; scarf_angle_threshold = 155
; scarf_joint_flow_ratio = 1
; scarf_joint_speed = 100%
; scarf_overhang_threshold = 40%
; seam_gap = 10%
; seam_position = aligned
; seam_slope_conditional = 0
; seam_slope_entire_loop = 0
; seam_slope_inner_walls = 0
; seam_slope_min_length = 20
; seam_slope_start_height = 0
; seam_slope_steps = 10
; seam_slope_type = none
; silent_mode = 0
; single_extruder_multi_material = 1
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 2
; skirt_loops = 0
; skirt_speed = 50
; slice_closing_radius = 0.049
; slicing_mode = regular
; slow_down_for_layer_cooling = 1
; slow_down_layer_time = 5
; slow_down_layers = 2
; slow_down_min_speed = 10
; slowdown_for_curled_perimeters = 0
; small_area_infill_flow_compensation = 0
; small_area_infill_flow_compensation_model = 0,0;"\n0.2,0.4444";"\n0.4,0.6145";"\n0.6,0.7059";"\n0.8,0.7619";"\n1.5,0.8571";"\n2,0.8889";"\n3,0.9231";"\n5,0.9520";"\n10,1"
; small_perimeter_speed = 50%
; small_perimeter_threshold = 0
; solid_infill_filament = 1
; sparse_infill_acceleration = 100%
; sparse_infill_density = 100%
; sparse_infill_filament = 1
; sparse_infill_line_width = 0.5
; sparse_infill_pattern = alignedrectilinear
; sparse_infill_speed = 30
; spiral_mode = 0
; spiral_mode_max_xy_smoothing = 200%
; spiral_mode_smooth = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_end_points = 30x-3,54x245
; support_air_filtration = 0
; support_angle = 0
; support_base_pattern = rectilinear
; support_base_pattern_spacing = 2.5
; support_bottom_interface_spacing = 0.5
; support_bottom_z_distance = 0.2
; support_chamber_temp_control = 0
; support_critical_regions_only = 0
; support_expansion = 0
; support_filament = 0
; support_interface_bottom_layers = -1
; support_interface_filament = 0
; support_interface_loop_pattern = 0
; support_interface_not_for_body = 1
; support_interface_pattern = auto
; support_interface_spacing = 0.5
; support_interface_speed = 80
; support_interface_top_layers = 2
; support_line_width = 0.5
; support_material_interface_fan_speed = -1
; support_multi_bed_types = 0
; support_object_xy_distance = 0.35
; support_on_build_plate_only = 0
; support_remove_small_overhang = 1
; support_speed = 200
; support_style = grid
; support_threshold_angle = 45
; support_top_z_distance = 0.15
; support_type = normal(auto)
; temperature_vitrification = 80
; template_custom_gcode = 
; textured_plate_temp = 70
; textured_plate_temp_initial_layer = 70
; thick_bridges = 0
; thick_internal_bridges = 1
; thumbnails = 96x96,300x300
; thumbnails_format = PNG
; time_cost = 0
; time_lapse_gcode = TIMELAPSE_TAKE_FRAME
; timelapse_type = 0
; top_shell_layers = 1
; top_shell_thickness = 0.8
; top_solid_infill_flow_ratio = 1
; top_surface_acceleration = 5000
; top_surface_jerk = 7
; top_surface_line_width = 0.5
; top_surface_pattern = alignedrectilinear
; top_surface_speed = 30
; travel_acceleration = 5000
; travel_jerk = 8
; travel_speed = 300
; travel_speed_z = 0
; tree_support_adaptive_layer_height = 1
; tree_support_angle_slow = 25
; tree_support_auto_brim = 1
; tree_support_branch_angle = 40
; tree_support_branch_angle_organic = 40
; tree_support_branch_diameter = 5
; tree_support_branch_diameter_angle = 5
; tree_support_branch_diameter_double_wall = 3
; tree_support_branch_diameter_organic = 2
; tree_support_branch_distance = 5
; tree_support_branch_distance_organic = 1
; tree_support_brim_width = 3
; tree_support_tip_diameter = 0.8
; tree_support_top_rate = 30%
; tree_support_wall_count = 0
; upward_compatible_machine = 
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; wall_direction = auto
; wall_distribution_count = 1
; wall_filament = 1
; wall_generator = classic
; wall_loops = 2
; wall_sequence = inner wall/outer wall
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_before_external_loop = 0
; wipe_distance = 1
; wipe_on_loops = 0
; wipe_speed = 80%
; wipe_tower_bridging = 10
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_x = 0.000
; wipe_tower_y = 250.000
; wiping_volumes_extruders = 70,70,70,70,70,70,70,70,70,70
; xy_contour_compensation = 0
; xy_hole_compensation = 0
; z_hop = 0.2
; z_hop_types = Normal Lift
; z_offset = 0
; first_layer_bed_temperature = 80
; bed_shape = 0x0,220x0,220x220,0x220
; first_layer_temperature = 235
; first_layer_height = 0.200
; CONFIG_BLOCK_END


